//Generated By Manifestor
require("/Users/rikky/WebstormProjects/service-manifest/src/ManifestGenerator.js");
require("/Users/rikky/WebstormProjects/service-manifest/src/Manifestor.js");
require("/Users/rikky/WebstormProjects/service-manifest/src/Scanner.js");
require("/Users/rikky/WebstormProjects/service-manifest/bin/manifestor.js");