const fs = require('fs');
const util = require('util');
const writeFile = util.promisify(fs.writeFile);

class ManifestGenerator {

    setOutput(output) {
        this.output = output;
        return this;
    }

    async generate(services) {
        let content = services.map(file => `require("${process.cwd() + '/' + file}");`).join("\n");

        await writeFile(this.output, "//Generated By Manifestor\n" + content);
    }
}

module.exports = ManifestGenerator;
